# Generated by Django 2.1.7 on 2019-05-21 10:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 10, 25, 3, 89904, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentonpost',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 10, 25, 3, 90370, tzinfo=utc)),
        ),
    ]
