# Generated by Django 2.1.7 on 2019-05-21 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20190521_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 10, 31, 6, 204662, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentonpost',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 10, 31, 6, 205152, tzinfo=utc)),
        ),
    ]
