# Generated by Django 2.1.7 on 2019-05-22 10:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20190521_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth_app.UserProfileInfo'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 10, 29, 56, 90443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentonpost',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 10, 29, 56, 91018, tzinfo=utc)),
        ),
    ]
